_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2y$12$Dk/YM7YFjRkYcd5lO6HBtO7dRzZVd8nP5hXuhxUe7FQy5XnvX9Z1i"
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"

kibanaserver:
  hash: "$2y$12$Dk/YM7YFjRkYcd5lO6HBtO7dRzZVd8nP5hXuhxUe7FQy5XnvX9Z1i"
  reserved: true
  description: "Demo kibanaserver user"

kibanaro:
  hash: "$2y$12$Dk/YM7YFjRkYcd5lO6HBtO7dRzZVd8nP5hXuhxUe7FQy5XnvX9Z1i"
  reserved: false
  backend_roles:
  - "kibanauser"
  - "readall"
  attributes:
    attribute1: "value1"
    attribute2: "value2"
    attribute3: "value3"
  description: "Demo kibanaro user"

logstash:
  hash: "$2y$12$Dk/YM7YFjRkYcd5lO6HBtO7dRzZVd8nP5hXuhxUe7FQy5XnvX9Z1i"
  reserved: false
  backend_roles:
  - "logstash"
  description: "Demo logstash user"

readall:
  hash: "$2y$12$Dk/YM7YFjRkYcd5lO6HBtO7dRzZVd8nP5hXuhxUe7FQy5XnvX9Z1i"
  reserved: false
  backend_roles:
  - "readall"
  description: "Demo readall user"

snapshotrestore:
  hash: "$2y$12$Dk/YM7YFjRkYcd5lO6HBtO7dRzZVd8nP5hXuhxUe7FQy5XnvX9Z1i"
  reserved: false
  backend_roles:
  - "snapshotrestore"
  description: "Demo snapshotrestore user"

