name: CI/CD Wazuh Stack

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI - Validate Wazuh Stack
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Validate YAML files
        run: |
          echo "[INFO] Starting YAML validation at $(date)"
          set -e
          error=0

          # Lint YAML files
          for file in $(find config -type f -name "*.yml"); do
            echo "[INFO] Linting $file..."
            yamllint "$file" || error=1
          done

          # Python parse check
          for file in $(find config -type f -name "*.yml"); do
            echo "[INFO] Parsing $file..."
            python3 -c "import yaml; yaml.safe_load(open('$file'))" || error=1
          done

          if [ $error -eq 1 ]; then
            echo "❌ YAML validation failed. Fix the errors above."
            exit 1
          else
            echo "✅ All YAML files are valid and well-formed."
          fi

  cd:
    name: CD - Deploy Wazuh Stack
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Wazuh stack
        run: |
          echo "[INFO] Deploying Wazuh stack on Docker Swarm at $(date)..."
          set -e
          docker stack deploy -c stack.yml wazuh
          echo "[SUCCESS] Wazuh stack deployed successfully!"

